### PR TITLE
[compiler-explorer] Add GCC 9.4, 9.5, 10.4 and update trunk for Arm compilers

### PR DESCRIPTION
**Pull request by TamarChristinaArm**
This adds GCC 9.4, 9.5 and 10.4 for both Arm64 and Arm.

It also updates trunk builds to stop building gprofng which has been
failing for a few days now but that isn't required for these builds.

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Thanks Tamar!

**Comment by mattgodbolt** [comment]
Once the image has built I'll kick off the builds for these.

**Comment by mattgodbolt** [comment]
Once the image has built I'll kick off the builds for these.

**Comment by mattgodbolt** [comment]
Once the image has built I'll kick off the builds for these.

**Comment by mattgodbolt** [comment]
Once the image has built I'll kick off the builds for these.

**Comment by TamarChristinaArm** [comment]
Thank you!

**Pull request merged**
