### PR TITLE
[RISC-V] Turn off autoconf and automake

### PR DESCRIPTION
**Pull request by cmuellner**
This turns off autoconf and automake for RISC-V as it is not required.

The configuration has been tested successfully on Ubuntu 18.04
with crosstools-ng (using commit fcf3233 as defined in the Dockerfile).

Related to #965.

### CODE REVIEW

**Review by mattgodbolt — APPROVED** [review]
Great stuff: thanks!

**Comment by mattgodbolt** [comment]
Would it be possible for you to fix up the RISCV-32 too?

**Comment by mattgodbolt** [comment]
Docker image building, then I'll kick off a build! I'm excited, thanks!

**Comment by mattgodbolt** [comment]
So, unfortunately this failed in the same way as before:

```
[INFO ]  Installing libiconv for host: done in 0.01s (at 02:33)
[INFO ]  =================================================================
[INFO ]  Installing gettext for host
[EXTRA]    Skipping (included in GNU C library)
[INFO ]  Installing gettext for host: done in 0.01s (at 02:33)
[INFO ]  =================================================================
[INFO ]  Installing binutils for host
[EXTRA]    Configuring binutils
[EXTRA]    Building binutils
[EXTRA]    Installing binutils
[INFO ]  Installing binutils for host: done in 32.15s (at 03:05)
[INFO ]  =================================================================
[INFO ]  Installing pass-1 core C gcc compiler
[EXTRA]    Configuring core C gcc compiler
[EXTRA]    Building gcc
[EXTRA]    Installing gcc
[EXTRA]    Housekeeping for core gcc compiler
[EXTRA]       '' --> lib (gcc)   lib (os)
[INFO ]  Installing pass-1 core C gcc compiler: done in 136.46s (at 05:21)
[INFO ]  =================================================================
[INFO ]  Installing kernel headers
[EXTRA]    Installing kernel headers
[ERROR]    make[3]: *** [headers_install] Error 127
[ERROR]    make[2]: *** [__sub-make] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing kernel headers'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: do_kernel_headers[scripts/build/kernel/linux.sh@64]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@695]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >> NOTE: Your configuration includes features marked EXPERIMENTAL.
[ERROR]  >> Before submitting a bug report, try to reproduce it without enabling
[ERROR]  >> any experimental features. Otherwise, you'll need to debug it
[ERROR]  >> and present an explanation why it is a bug in crosstool-NG - or
[ERROR]  >> preferably, a fix.
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]   
[ERROR]  (elapsed: 5:27.29)
[05:28] / /opt/crosstool-ng-latest/bin/ct-ng:261: recipe for target 'build' failed
make[1]: *** [build] Error 2
/opt/crosstool-ng-latest/bin/ct-ng:265: recipe for target 'build.16' failed
make: *** [build.16] Error 2
Traceback (most recent call last):
```

And that's where I stopped looking last time, hoping someone could show this working in the `Dockerfile` :(

**Comment by cmuellner** [comment]
Would it be possible to get the 'build.log' file?

**Comment by mattgodbolt** [comment]
Not easily; I shut down the instance after. The hope is you can test using docker (which should be 100% reproducible) so we know ahead of time. I can take a look at running it again.

**Comment by cmuellner** [comment]
I've just built the Docker image here. And executed `./build.sh riscv64 10.2.0` inside.
Here is the actual error:
```
[ALL  ]    /bin/sh: 1: rsync: not found
```

I will install `rsync`, try again, and make a new PR, which adds this to the `Dockerfile`.

**Comment by cmuellner** [comment]
Build inside the Docker image was successful with the following PR: https://github.com/compiler-explorer/gcc-cross-builder/pull/6

**Comment by mattgodbolt** [comment]
Amazing stuff - thank you. Just built successfully! I'll let you know when the compiler is live!

**Comment by mattgodbolt** [comment]
```
$ /opt/compiler-explorer/riscv64/gcc-10.2.0/riscv64-unknown-linux-gnu/bin/riscv64-unknown-linux-gnu-g++ --version
riscv64-unknown-linux-gnu-g++ (crosstool-NG UNKNOWN) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
yay

**Comment by mattgodbolt** [comment]
This, and the 32-bit version are now live

**Comment by cmuellner** [comment]
Yay!
Thank you so much!

**Pull request merged**
