### PR TITLE
Add GCC 11.1 Arm64 and Arm (A-Profile)

### PR DESCRIPTION
**Pull request by TamarChristinaArm**
Hi All,

This adds new configurations for 

* Arm64 GCC 11.1.0

and

* Arm GCC 11.1.0

using latest released binutils and glibc.

Thanks,
Tamar

### CODE REVIEW

**Comment by TamarChristinaArm** [comment]
friendly Ping :)

**Comment by mattgodbolt** [comment]
oh my! I'm sorry about this, it got lost!

**Review by mattgodbolt — APPROVED** [review]
Will build asap

**Comment by TamarChristinaArm** [comment]
Cheers, thanks! :)

**Comment by mattgodbolt** [comment]
For those watching, I'm running:
```
$ ce builder exec -- sudo docker run --rm --name gcc.cross.build -v/home/ubuntu/.s3cfg:/home/gcc-user/.s3cfg:ro compilerexplorer/gcc-cross-builder bash build.sh arm 11.1.0 s3://compiler-explorer/opt/
```

**Comment by mattgodbolt** [comment]
both arm and arm64 have been built now - yay

**Pull request merged**
